# I could inherit from this instead if I want to add a different colorscheme.
theme = "base16_transparent"

[editor]
line-number = "relative"
mouse = true

[keys.normal]
C-s = ":w" # Maps Ctrl-s to save
"ret" = ["open_below", "normal_mode"] 
# Maps the enter key to open_below then re-enter normal mode



[keys.insert]
j = { k =  "normal_mode"  }
