# I could inherit from this instead if I want to add a different colorscheme.
theme = "everforest-dark"

[editor]
line-number = "relative"
mouse = true
auto-save = true
idle-timeout = 300
shell = ["zsh", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
# C-s = ":w" # Maps Ctrl-s to save
"ret" = ["open_below", "normal_mode"] 
# Maps the enter key to open_below then re-enter normal mode
"$" = "goto_line_end"

[keys.select]
"$" = "goto_line_end"

[keys.insert]
j = { k =  "normal_mode"  }
