[[language]]
name = "git-commit"
rulers = []

[[language]]
name = "quarto-markdown"
scope = "source.qmd"
injection-regex = "(q|Q)md"
file-types = ["qmd", "Qmd"]
roots = []
indent = { tab-width = 2, unit = "  " }
grammar = "markdown"

[[language]]
name = "python"
auto-format = false

[language.formatter]
command = "black"
args = [
  "-",
  "--quiet",
]
